using MediaBrowser.Common.Configuration;
using PersonCleaner.Storage;
using SQLitePCL.pretty;
using SQLitePCLEx;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;

namespace PersonCleaner.Housekeeping
{
    public sealed class HousekeepingResultRow
    {
        public long ProposalId { get; set; }
        public long EmbyPersonId { get; set; }
        public string Person { get; set; }
        public string Recommendation { get; set; }
        public string SignalType { get; set; }
        public string Provider { get; set; }
        public string CurrentValue { get; set; }
        public string ProposedValue { get; set; }
        public string CurrentEmbyIds { get; set; }
        public string ProposedEmbyIds { get; set; }
        public string CurrentName { get; set; }
        public string ProposedName { get; set; }
        public string CurrentTmdbIds { get; set; }
        public string ProposedTmdbIds { get; set; }
        public string CurrentTvdbIds { get; set; }
        public string ProposedTvdbIds { get; set; }
        public string CurrentImdbIds { get; set; }
        public string ProposedImdbIds { get; set; }
        public string LinkedMediaEvidence { get; set; }
        public double Confidence { get; set; }
        public int LinkedMedia { get; set; }
        public int CheckedMedia { get; set; }
        public string Evidence { get; set; }
        public string ReviewStatus { get; set; }
    }

    internal sealed class HousekeepingRepository : IDisposable
    {
        private const int BatchSize = 1000;
        private readonly IDatabaseConnection db;

        public HousekeepingRepository(IApplicationPaths paths)
            : this(ArchiveDatabase.ResolvePath(paths))
        {
        }

        internal HousekeepingRepository(string path)
        {
            ArchiveDatabase.RequireExisting(path);
            db=SQLite3.Open(path,ConnectionFlags.ReadWrite|ConnectionFlags.PrivateCache|ConnectionFlags.NoMutex,null,new Dictionary<string,delegate_collation>(),new Dictionary<Tuple<string,int>,Action<IReadOnlyList<sqlite3_value>,sqlite3_context>>(),true,false);
            db.Execute("PRAGMA busy_timeout=5000"); db.Execute("PRAGMA synchronous=NORMAL");
            ArchiveDatabase.ValidateObjects(db,"housekeeping v3","housekeeping_run","housekeeping_signal","housekeeping_recommendation","truth_entity_delta","truth_identity_delta","truth_relationship_delta","housekeeping_latest_results","provider_identity_issue");
            ArchiveDatabase.ValidateMigrations(db,6);
        }

        public long Run(DateTime cutoff,CancellationToken token,Action<string,double,TimeSpan> report)
        {
            var clock=Stopwatch.StartNew(); long run=0;
            using(token.Register(()=>{try{db.Interrupt();}catch{}})) try
            {
                Phase(token,report,clock,"Creating experiment run",1); run=StartRun(cutoff);
                Phase(token,report,clock,"Normalizing provider identity status",4);
                Tx(x=>{IdentitySignals(x,run);MissingIdentitySignals(x,run);State(x,run,"provider-identity-status",5);});
                Phase(token,report,clock,"Auditing every current identity against linked media",5);Tx(x=>{UniversalIdentityAudits(x,run);State(x,run,"universal-identity-audit",10);});
                Phase(token,report,clock,"Building retained candidate/media evidence ledger",10);Tx(x=>{RelationshipSignals(x,run);State(x,run,"identity-and-relationship-evidence",14);});
                Reacquire("tmdb",run,token,report,clock,14,24);
                Reacquire("tvdb",run,token,report,clock,24,48);
                Phase(token,report,clock,"Evaluating media-backed TMDB replacements",48);Tx(x=>{MediaBackedTmdbReplacements(x,run);State(x,run,"media-backed-tmdb-replacements",49);});
                Phase(token,report,clock,"Evaluating retained provider candidates and Emby ownership",49);Tx(x=>{CandidateDecisions(x,run);State(x,run,"candidate-decisions",51);});
                Phase(token,report,clock,"Retaining universal identity-audit findings for case evidence",51);Tx(x=>State(x,run,"universal-audit-evidence",52));
                Phase(token,report,clock,"Finding provider identity issues",52);Tx(x=>{ProviderIssues(x,run);State(x,run,"provider-identity-issues",53);});
                Phase(token,report,clock,"Withholding or confirming unavailable-ID removals",53);Tx(x=>{UnavailableExplicit(x,run);State(x,run,"identity-decisions",54);});
                Phase(token,report,clock,"Evaluating provider renames from aggregated audit evidence",54);
                Tx(x=>{RenamesV3(x,run);State(x,run,"provider-renames",66);});
                Phase(token,report,clock,"Finding merge evidence",66);
                Tx(x=>{Merges(x,run);State(x,run,"merge-evidence",72);});
                Phase(token,report,clock,"Finding cross-provider split evidence",72);Tx(x=>{CrossProviderSplits(x,run);State(x,run,"cross-provider-split-evidence",78);});
                Phase(token,report,clock,"Finding same-provider linked-media partitions",78);Tx(x=>{SplitsV2(x,run);State(x,run,"split-evidence",84);});
                Phase(token,report,clock,"Consolidating detector findings into actionable review cases",84);Tx(x=>{ConsolidateReviewCases(x,run);State(x,run,"review-case-consolidation",90);});
                Phase(token,report,clock,"Creating delta truth",90); Tx(x=>DeltaTruth(x,run));
                Phase(token,report,clock,"Finalizing results",96); Tx(x=>Complete(x,run));
                token.ThrowIfCancellationRequested(); return run;
            }
            catch(SQLiteException) when(token.IsCancellationRequested){if(run!=0)Stop(run,"cancelled","SQLite interrupted by Emby cancellation");throw new OperationCanceledException("Housekeeping cancelled",token);}
            catch(OperationCanceledException){if(run!=0)Stop(run,"cancelled","Cancelled by Emby");throw;}
            catch(Exception ex){if(run!=0)Stop(run,"failed",ex.ToString());throw;}
        }

        private long StartRun(DateTime cutoff)
        {
            long id=0; var now=Now(); Tx(x=>{
                x.Execute("INSERT OR IGNORE INTO algorithm(name,version,code_hash,configuration_json) VALUES('person-housekeeping','normalized-v9','normalized-v9-actionable-review-cases','{\"humanReview\":true,\"deltaTruth\":true,\"batchSize\":1000,\"anchor\":\"emby-person-linked-media\",\"universalProviderAudit\":true,\"evidenceGapAcquisition\":true,\"relationshipEvidenceLedger\":true,\"providerIssues\":true,\"supportedExternalIdDiscovery\":true,\"anchoredProviderIssues\":true,\"configurableNameEquivalence\":true,\"providerConsensusRename\":true,\"actionableReviewCases\":true,\"providerMisattributionAdjudication\":true}')");
                Exec(x,"INSERT INTO experiment_run(algorithm_id,truth_id,observation_cutoff_utc,mask_policy_json,started_utc,status) SELECT algorithm_id,1,@cutoff,json_object('providerRequests','bounded-cached-evidence-gaps','auditScope','all-linked-emby-people-both-providers','givenNameEquivalences',@names),@now,'running' FROM algorithm WHERE name='person-housekeeping' AND version='normalized-v9'",s=>{s.TryBind("@cutoff",cutoff.ToString("o"));s.TryBind("@names",Plugin.Instance.Configuration.GivenNameEquivalences??string.Empty);s.TryBind("@now",now);}); id=LastId(x);
                Exec(x,"INSERT INTO housekeeping_run(run_id,algorithm_version,base_truth_id,phase,progress,status,observation_cutoff_utc,started_utc,heartbeat_utc) VALUES(@run,'normalized-v9',1,'starting',1,'running',@cutoff,@now,@now)",s=>{s.TryBind("@run",id);s.TryBind("@cutoff",cutoff.ToString("o"));s.TryBind("@now",now);});}); return id;
        }

        private static void IdentitySignals(IDatabaseConnection x,long run)=>Exec(x,@"INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,candidate_external_id,current_name,candidate_name,score,confidence,evidence_text,created_utc)
SELECT @run,p.emby_id,'emby:'||p.emby_id,'tmdb',CASE r.provenance WHEN 'direct' THEN 'identity-live' WHEN 'direct-unavailable' THEN 'identity-unavailable' ELSE 'identity-unresolved' END,p.tmdb_id,r.resolved_tmdb_id,p.name,e.name,CASE r.provenance WHEN 'direct' THEN 1 WHEN 'direct-unavailable' THEN 0 ELSE .5 END,CASE r.provenance WHEN 'direct' THEN .99 WHEN 'direct-unavailable' THEN .95 ELSE .25 END,'TMDB status: '||r.provenance,@now FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id LEFT JOIN tmdb_entity e ON e.entity_type='person' AND e.tmdb_id=r.resolved_tmdb_id WHERE p.item_type='person'
UNION ALL SELECT @run,p.emby_id,'emby:'||p.emby_id,'tvdb',CASE r.provenance WHEN 'direct' THEN 'identity-live' WHEN 'direct-unavailable' THEN 'identity-unavailable' ELSE 'identity-unresolved' END,p.tvdb_id,r.resolved_tvdb_id,p.name,e.name,CASE r.provenance WHEN 'direct' THEN 1 WHEN 'direct-unavailable' THEN 0 ELSE .5 END,CASE r.provenance WHEN 'direct' THEN .99 WHEN 'direct-unavailable' THEN .95 ELSE .25 END,'TVDB status: '||r.provenance,@now FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id LEFT JOIN tvdb_entity e ON e.entity_type='person' AND e.tvdb_id=r.resolved_tvdb_id WHERE p.item_type='person'",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void MissingIdentitySignals(IDatabaseConnection x,long run)=>Exec(x,@"INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,current_name,score,confidence,evidence_text,created_utc)
SELECT @run,p.emby_id,'emby:'||p.emby_id,'tmdb',CASE WHEN p.tmdb_id IS NULL THEN 'identity-missing' ELSE 'identity-unresolved' END,p.tmdb_id,p.name,0,.2,CASE WHEN p.tmdb_id IS NULL THEN 'No TMDB person ID is assigned' ELSE 'No TMDB resolution observation is archived' END,@now FROM emby_item p LEFT JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.emby_id IS NULL
UNION ALL SELECT @run,p.emby_id,'emby:'||p.emby_id,'tvdb',CASE WHEN p.tvdb_id IS NULL THEN 'identity-missing' ELSE 'identity-unresolved' END,p.tvdb_id,p.name,0,.2,CASE WHEN p.tvdb_id IS NULL THEN 'No TVDB person ID is assigned' ELSE 'No TVDB resolution observation is archived' END,@now FROM emby_item p LEFT JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.emby_id IS NULL",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void UniversalIdentityAudits(IDatabaseConnection x,long run)
        {
            Exec(x,@"WITH media AS (
SELECT p.emby_id person_id,p.name current_name,p.tmdb_id current_id,er.media_emby_id,m.item_type media_type,coalesce(m.tmdb_id,mr.resolved_tmdb_id) production_id,coalesce(json_extract(me.raw_json,'$.show_id'),parent.tmdb_id,pr.resolved_tmdb_id) series_id,me.tmdb_id checked_id,exact.person_tmdb_id exact_person,broad.person_tmdb_id broad_person
FROM emby_item p LEFT JOIN emby_relationship er ON er.person_emby_id=p.emby_id LEFT JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN tmdb_entity me ON me.tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND me.entity_type=m.item_type LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN tmdb_item_resolution pr ON pr.emby_id=parent.emby_id LEFT JOIN tmdb_credit exact ON exact.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND exact.production_type=m.item_type AND exact.person_tmdb_id=p.tmdb_id LEFT JOIN tmdb_credit broad ON m.item_type='episode' AND broad.production_tmdb_id=coalesce(json_extract(me.raw_json,'$.show_id'),parent.tmdb_id,pr.resolved_tmdb_id) AND broad.production_type='series' AND broad.person_tmdb_id=p.tmdb_id WHERE p.item_type='person'), classified AS (
SELECT media.*,CASE WHEN media_emby_id IS NULL THEN 'no-media' WHEN production_id IS NULL THEN 'unresolved' WHEN exact_person IS NOT NULL THEN 'exact' WHEN media_type='episode' AND broad_person IS NOT NULL THEN 'broader' WHEN media_type='episode' AND EXISTS(SELECT 1 FROM tmdb_fetch_cache f WHERE f.cache_key='episode-credits:'||production_id AND f.state='success') THEN 'not-present' WHEN media_type<>'episode' AND checked_id IS NOT NULL THEN 'not-present' ELSE 'unchecked' END result FROM media), audit AS (
SELECT person_id,current_name,current_id,count(DISTINCT media_emby_id) linked,count(DISTINCT CASE WHEN result IN('exact','broader','not-present') THEN media_emby_id END) checked,count(DISTINCT CASE WHEN result='exact' THEN media_emby_id END) exact_count,count(DISTINCT CASE WHEN result='broader' THEN media_emby_id END) broader_count,count(DISTINCT CASE WHEN result='not-present' THEN media_emby_id END) not_present,count(DISTINCT CASE WHEN result IN('unresolved','unchecked') THEN media_emby_id END) unresolved FROM classified GROUP BY person_id,current_name,current_id)
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,current_name,linked_media_count,checked_media_count,supported_media_count,score,confidence,evidence_text,evidence_json,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tmdb',CASE WHEN current_id IS NULL THEN 'identity-audit-missing' WHEN linked=0 THEN 'identity-audit-unlinked' WHEN exact_count+broader_count>0 AND not_present=0 THEN 'identity-supported' WHEN exact_count+broader_count>0 THEN 'identity-partially-supported' WHEN checked=0 THEN 'identity-audit-incomplete' ELSE 'identity-unsupported' END,current_id,current_name,linked,checked,exact_count+broader_count,CASE WHEN linked=0 THEN NULL ELSE (exact_count+.9*broader_count)/linked END,CASE WHEN linked=0 THEN .25 WHEN exact_count+broader_count>0 AND not_present=0 THEN .95 WHEN exact_count+broader_count>0 THEN .65 WHEN checked=linked THEN .2 ELSE .3 END,'TMDB identity audit: linked='||linked||'; checked='||checked||'; exact='||exact_count||'; broader-series='||broader_count||'; not-present='||not_present||'; unresolved='||unresolved,json_object('linked',linked,'checked',checked,'exact_scope',exact_count,'broader_series_scope',broader_count,'not_present',not_present,'unresolved',unresolved),@now FROM audit",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
            Exec(x,@"WITH episode_series AS (SELECT DISTINCT production_tvdb_id,source_tvdb_id FROM tvdb_credit_observation WHERE production_type='episode' AND source_entity_type='series'), media AS (
SELECT p.emby_id person_id,p.name current_name,p.tvdb_id current_id,er.media_emby_id,m.item_type media_type,coalesce(m.tvdb_id,mr.resolved_tvdb_id) production_id,coalesce(parent.tvdb_id,pr.resolved_tvdb_id,series_credit.source_tvdb_id) series_id,me.tvdb_id checked_id,exact.person_tvdb_id exact_person,broad.person_tvdb_id broad_person
FROM emby_item p LEFT JOIN emby_relationship er ON er.person_emby_id=p.emby_id LEFT JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN tvdb_entity me ON me.tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND me.entity_type=m.item_type LEFT JOIN episode_series series_credit ON m.item_type='episode' AND series_credit.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN item_resolution pr ON pr.emby_id=parent.emby_id LEFT JOIN credit exact ON exact.subject_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND exact.subject_type=m.item_type AND exact.person_tvdb_id=p.tvdb_id LEFT JOIN credit broad ON m.item_type='episode' AND broad.subject_tvdb_id=coalesce(parent.tvdb_id,pr.resolved_tvdb_id,series_credit.source_tvdb_id) AND broad.subject_type='series' AND broad.person_tvdb_id=p.tvdb_id WHERE p.item_type='person'), classified AS (
SELECT media.*,CASE WHEN media_emby_id IS NULL THEN 'no-media' WHEN production_id IS NULL THEN 'unresolved' WHEN exact_person IS NOT NULL THEN 'exact' WHEN media_type='episode' AND broad_person IS NOT NULL THEN 'broader' WHEN checked_id IS NOT NULL THEN 'not-present' ELSE 'unchecked' END result FROM media), audit AS (
SELECT person_id,current_name,current_id,count(DISTINCT media_emby_id) linked,count(DISTINCT CASE WHEN result IN('exact','broader','not-present') THEN media_emby_id END) checked,count(DISTINCT CASE WHEN result='exact' THEN media_emby_id END) exact_count,count(DISTINCT CASE WHEN result='broader' THEN media_emby_id END) broader_count,count(DISTINCT CASE WHEN result='not-present' THEN media_emby_id END) not_present,count(DISTINCT CASE WHEN result IN('unresolved','unchecked') THEN media_emby_id END) unresolved FROM classified GROUP BY person_id,current_name,current_id)
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,current_name,linked_media_count,checked_media_count,supported_media_count,score,confidence,evidence_text,evidence_json,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tvdb',CASE WHEN current_id IS NULL THEN 'identity-audit-missing' WHEN linked=0 THEN 'identity-audit-unlinked' WHEN exact_count+broader_count>0 AND not_present=0 THEN 'identity-supported' WHEN exact_count+broader_count>0 THEN 'identity-partially-supported' WHEN checked=0 THEN 'identity-audit-incomplete' ELSE 'identity-unsupported' END,current_id,current_name,linked,checked,exact_count+broader_count,CASE WHEN linked=0 THEN NULL ELSE (exact_count+.9*broader_count)/linked END,CASE WHEN linked=0 THEN .25 WHEN exact_count+broader_count>0 AND not_present=0 THEN .95 WHEN exact_count+broader_count>0 THEN .65 WHEN checked=linked THEN .2 ELSE .3 END,'TVDB identity audit: linked='||linked||'; checked='||checked||'; exact='||exact_count||'; broader-series='||broader_count||'; not-present='||not_present||'; unresolved='||unresolved,json_object('linked',linked,'checked',checked,'exact_scope',exact_count,'broader_series_scope',broader_count,'not_present',not_present,'unresolved',unresolved),@now FROM audit",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
        }

        private static void RelationshipSignals(IDatabaseConnection x,long run)
        {
            Exec(x,@"WITH media AS (
SELECT p.emby_id person_id,p.name current_name,p.tmdb_id current_id,er.media_emby_id,m.item_type media_type,coalesce(nullif(er.role,''),er.person_type) relationship_role,coalesce(m.tmdb_id,mr.resolved_tmdb_id) production_id,coalesce(parent.tmdb_id,pr.resolved_tmdb_id,json_extract(me.raw_json,'$.show_id')) series_id,m.name media_name
FROM emby_item p JOIN tmdb_item_resolution dead ON dead.emby_id=p.emby_id AND dead.provenance='direct-unavailable' JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN tmdb_entity me ON me.tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND me.entity_type=m.item_type LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN tmdb_item_resolution pr ON pr.emby_id=parent.emby_id WHERE p.item_type='person')
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,current_name,media_emby_id,media_type,relationship_role,checked_media_count,evidence_text,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tmdb',CASE WHEN production_id IS NULL THEN 'media-unavailable' WHEN media_type='episode' AND EXISTS(SELECT 1 FROM tmdb_fetch_cache f WHERE f.cache_key='episode-credits:'||production_id AND f.state='success') THEN 'media-checked' WHEN media_type<>'episode' AND EXISTS(SELECT 1 FROM tmdb_entity e WHERE e.tmdb_id=media.production_id AND e.entity_type=media.media_type) THEN 'media-checked' ELSE 'unchecked' END,current_id,current_name,media_emby_id,media_type,relationship_role,CASE WHEN production_id IS NOT NULL AND (media_type='episode' AND EXISTS(SELECT 1 FROM tmdb_fetch_cache f WHERE f.cache_key='episode-credits:'||production_id AND f.state='success') OR media_type<>'episode' AND EXISTS(SELECT 1 FROM tmdb_entity e WHERE e.tmdb_id=media.production_id AND e.entity_type=media.media_type)) THEN 1 ELSE 0 END,'TMDB media '||media_emby_id||' '||coalesce(media_name,'')||'; provider production='||coalesce(production_id,'unresolved'),@now FROM media",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
            Exec(x,@"WITH media AS (
SELECT p.emby_id person_id,p.name current_name,p.tvdb_id current_id,er.media_emby_id,m.item_type media_type,coalesce(nullif(er.role,''),er.person_type) relationship_role,coalesce(m.tvdb_id,mr.resolved_tvdb_id) production_id,coalesce(parent.tvdb_id,pr.resolved_tvdb_id,(SELECT c.source_tvdb_id FROM tvdb_credit_observation c WHERE c.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND c.production_type='episode' AND c.source_entity_type='series' LIMIT 1)) series_id,m.name media_name
FROM emby_item p JOIN item_resolution dead ON dead.emby_id=p.emby_id AND dead.provenance='direct-unavailable' JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN item_resolution pr ON pr.emby_id=parent.emby_id WHERE p.item_type='person')
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,current_name,media_emby_id,media_type,relationship_role,checked_media_count,evidence_text,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tvdb',CASE WHEN production_id IS NULL THEN 'media-unavailable' WHEN EXISTS(SELECT 1 FROM tvdb_entity e WHERE e.tvdb_id=media.production_id AND e.entity_type=media.media_type) THEN 'media-checked' ELSE 'unchecked' END,current_id,current_name,media_emby_id,media_type,relationship_role,CASE WHEN production_id IS NOT NULL AND EXISTS(SELECT 1 FROM tvdb_entity e WHERE e.tvdb_id=media.production_id AND e.entity_type=media.media_type) THEN 1 ELSE 0 END,'TVDB media '||media_emby_id||' '||coalesce(media_name,'')||'; provider production='||coalesce(production_id,'unresolved'),@now FROM media",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
            Exec(x,@"WITH candidates AS (SELECT rc.emby_id,rc.tmdb_id candidate_id,rc.name candidate_name FROM tmdb_resolution_candidate rc), media AS (
SELECT p.emby_id person_id,p.name current_name,p.tmdb_id current_id,c.candidate_id,c.candidate_name,er.media_emby_id,m.item_type media_type,coalesce(nullif(er.role,''),er.person_type) relationship_role,coalesce(m.tmdb_id,mr.resolved_tmdb_id) production_id,coalesce(parent.tmdb_id,pr.resolved_tmdb_id,json_extract(me.raw_json,'$.show_id')) series_id,m.name media_name
FROM emby_item p JOIN candidates c ON c.emby_id=p.emby_id JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN tmdb_entity me ON me.tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND me.entity_type=m.item_type LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN tmdb_item_resolution pr ON pr.emby_id=parent.emby_id), classified AS (
SELECT media.*,CASE WHEN production_id IS NULL THEN 'media-unavailable' WHEN EXISTS(SELECT 1 FROM tmdb_credit_observation c WHERE c.production_tmdb_id=media.production_id AND c.production_type=media.media_type AND c.person_tmdb_id=media.candidate_id) THEN 'confirmed-exact-scope' WHEN media_type='episode' AND series_id IS NOT NULL AND EXISTS(SELECT 1 FROM tmdb_credit_observation c WHERE c.production_tmdb_id=media.series_id AND c.production_type='series' AND c.person_tmdb_id=media.candidate_id) THEN 'confirmed-broader-series-scope' WHEN media_type='episode' AND EXISTS(SELECT 1 FROM tmdb_fetch_cache f WHERE f.cache_key='episode-credits:'||production_id AND f.state='success') THEN 'not-present' WHEN media_type<>'episode' AND EXISTS(SELECT 1 FROM tmdb_entity e WHERE e.tmdb_id=media.production_id AND e.entity_type=media.media_type) THEN 'not-present' ELSE 'unchecked' END result,
coalesce((SELECT c.job_or_character FROM tmdb_credit_observation c WHERE c.production_tmdb_id=media.production_id AND c.production_type=media.media_type AND c.person_tmdb_id=media.candidate_id LIMIT 1),(SELECT c.job_or_character FROM tmdb_credit_observation c WHERE media.media_type='episode' AND c.production_tmdb_id=media.series_id AND c.production_type='series' AND c.person_tmdb_id=media.candidate_id LIMIT 1)) provider_role FROM media)
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,candidate_external_id,current_name,candidate_name,media_emby_id,media_type,relationship_role,provider_role,linked_media_count,checked_media_count,supported_media_count,score,confidence,evidence_text,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tmdb',result,current_id,candidate_id,current_name,candidate_name,media_emby_id,media_type,relationship_role,provider_role,1,CASE WHEN result IN('confirmed-exact-scope','confirmed-broader-series-scope','not-present') THEN 1 ELSE 0 END,CASE WHEN result LIKE 'confirmed-%' THEN 1 ELSE 0 END,CASE result WHEN 'confirmed-exact-scope' THEN 1 WHEN 'confirmed-broader-series-scope' THEN .9 WHEN 'not-present' THEN 0 ELSE NULL END,CASE result WHEN 'confirmed-exact-scope' THEN .95 WHEN 'confirmed-broader-series-scope' THEN .85 WHEN 'not-present' THEN .8 ELSE .2 END,'TMDB candidate '||candidate_id||' '||coalesce(candidate_name,'')||' on Emby media '||media_emby_id||' '||coalesce(media_name,'')||': '||result||'; Emby role='||coalesce(relationship_role,'-')||'; provider role='||coalesce(provider_role,'-'),@now FROM classified",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
            Exec(x,@"WITH candidates AS (SELECT rc.emby_id,rc.tvdb_id candidate_id,rc.name candidate_name FROM resolution_candidate rc WHERE rc.entity_type='person'), media AS (
SELECT p.emby_id person_id,p.name current_name,p.tvdb_id current_id,c.candidate_id,c.candidate_name,er.media_emby_id,m.item_type media_type,coalesce(nullif(er.role,''),er.person_type) relationship_role,coalesce(m.tvdb_id,mr.resolved_tvdb_id) production_id,coalesce(parent.tvdb_id,pr.resolved_tvdb_id,(SELECT tc.source_tvdb_id FROM tvdb_credit_observation tc WHERE tc.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND tc.production_type='episode' AND tc.source_entity_type='series' LIMIT 1)) series_id,m.name media_name
FROM emby_item p JOIN candidates c ON c.emby_id=p.emby_id JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN emby_item parent ON parent.emby_id=m.parent_emby_id LEFT JOIN item_resolution pr ON pr.emby_id=parent.emby_id), classified AS (
SELECT media.*,CASE WHEN production_id IS NULL THEN 'media-unavailable' WHEN EXISTS(SELECT 1 FROM tvdb_credit_observation c WHERE c.production_tvdb_id=media.production_id AND c.production_type=media.media_type AND c.person_tvdb_id=media.candidate_id) THEN 'confirmed-exact-scope' WHEN media_type='episode' AND series_id IS NOT NULL AND EXISTS(SELECT 1 FROM tvdb_credit_observation c WHERE c.production_tvdb_id=media.series_id AND c.production_type='series' AND c.person_tvdb_id=media.candidate_id) THEN 'confirmed-broader-series-scope' WHEN EXISTS(SELECT 1 FROM tvdb_entity e WHERE e.tvdb_id=media.production_id AND e.entity_type=media.media_type) THEN 'not-present' ELSE 'unchecked' END result,
coalesce((SELECT c.role_name FROM tvdb_credit_observation c WHERE c.production_tvdb_id=media.production_id AND c.production_type=media.media_type AND c.person_tvdb_id=media.candidate_id LIMIT 1),(SELECT c.role_name FROM tvdb_credit_observation c WHERE media.media_type='episode' AND c.production_tvdb_id=media.series_id AND c.production_type='series' AND c.person_tvdb_id=media.candidate_id LIMIT 1)) provider_role FROM media)
INSERT INTO housekeeping_signal(run_id,person_emby_id,subject_truth_entity_id,provider,signal_type,current_external_id,candidate_external_id,current_name,candidate_name,media_emby_id,media_type,relationship_role,provider_role,linked_media_count,checked_media_count,supported_media_count,score,confidence,evidence_text,created_utc)
SELECT @run,person_id,'emby:'||person_id,'tvdb',result,current_id,candidate_id,current_name,candidate_name,media_emby_id,media_type,relationship_role,provider_role,1,CASE WHEN result IN('confirmed-exact-scope','confirmed-broader-series-scope','not-present') THEN 1 ELSE 0 END,CASE WHEN result LIKE 'confirmed-%' THEN 1 ELSE 0 END,CASE result WHEN 'confirmed-exact-scope' THEN 1 WHEN 'confirmed-broader-series-scope' THEN .9 WHEN 'not-present' THEN 0 ELSE NULL END,CASE result WHEN 'confirmed-exact-scope' THEN .95 WHEN 'confirmed-broader-series-scope' THEN .85 WHEN 'not-present' THEN .8 ELSE .2 END,'TVDB candidate '||candidate_id||' '||coalesce(candidate_name,'')||' on Emby media '||media_emby_id||' '||coalesce(media_name,'')||': '||result||'; Emby role='||coalesce(relationship_role,'-')||'; provider role='||coalesce(provider_role,'-'),@now FROM classified",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
        }

        private static void CandidateDecisions(IDatabaseConnection x,long run)
        {
            Exec(x,@"WITH stats AS (
SELECT person_emby_id,provider,current_external_id,candidate_external_id,max(current_name) current_name,max(candidate_name) candidate_name,count(DISTINCT media_emby_id) linked,sum(CASE WHEN signal_type IN('confirmed-exact-scope','confirmed-broader-series-scope','not-present') THEN 1 ELSE 0 END) checked,sum(CASE WHEN signal_type LIKE 'confirmed-%' THEN 1 ELSE 0 END) supported,sum(CASE signal_type WHEN 'confirmed-exact-scope' THEN 1.0 WHEN 'confirmed-broader-series-scope' THEN .9 ELSE 0 END) weighted
FROM housekeeping_signal WHERE run_id=@run AND candidate_external_id IS NOT NULL AND media_emby_id IS NOT NULL GROUP BY person_emby_id,provider,current_external_id,candidate_external_id), owners AS (
SELECT 'tmdb' provider,tmdb_id external_id,emby_id,name FROM emby_item WHERE item_type='person' AND tmdb_id IS NOT NULL UNION ALL SELECT 'tvdb',tvdb_id,emby_id,name FROM emby_item WHERE item_type='person' AND tvdb_id IS NOT NULL), owned AS (
SELECT s.*,o.emby_id owner_emby_id,o.name owner_name FROM stats s JOIN owners o ON o.provider=s.provider AND o.external_id=s.candidate_external_id AND o.emby_id<>s.person_emby_id WHERE s.supported>0 AND s.candidate_external_id<>coalesce(s.current_external_id,''))
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,person_emby_id,'emby:'||person_emby_id,'merge','review-merge','candidate-owned-by-emby',provider,CASE WHEN person_emby_id<owner_emby_id THEN person_emby_id||','||owner_emby_id ELSE owner_emby_id||','||person_emby_id END,candidate_external_id,linked,checked,supported,min(.97,.72+.18*weighted/max(1,linked)),'Candidate '||upper(provider)||' ID '||candidate_external_id||' ('||coalesce(candidate_name,'')||') is directly supported on '||supported||' linked media for Emby '||person_emby_id||' and is already assigned to Emby '||owner_emby_id||' ('||coalesce(owner_name,'')||'). Review relationship reassignment and choose a survivor; do not remove the unavailable ID in isolation.',@now FROM owned
WHERE NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.recommendation_type='review-merge' AND h.provider=owned.provider AND ((h.current_value=owned.person_emby_id||','||owned.owner_emby_id) OR (h.current_value=owned.owner_emby_id||','||owned.person_emby_id)))",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
            Exec(x,"DELETE FROM housekeeping_recommendation WHERE run_id=@run AND recommendation_type='replace-provider-id' AND EXISTS(SELECT 1 FROM housekeeping_recommendation m WHERE m.run_id=@run AND m.recommendation_type='review-merge' AND m.provider=housekeeping_recommendation.provider AND m.proposed_value=housekeeping_recommendation.proposed_value AND (','||m.current_value||',') LIKE '%,'||housekeeping_recommendation.person_emby_id||',%')",s=>s.TryBind("@run",run));
            Exec(x,@"WITH positives AS (
SELECT s.person_emby_id,s.provider,s.current_external_id,s.candidate_external_id,count(DISTINCT s.media_emby_id) linked,count(DISTINCT CASE WHEN s.signal_type IN('confirmed-exact-scope','confirmed-broader-series-scope','not-present') THEN s.media_emby_id END) checked,count(DISTINCT CASE WHEN s.signal_type LIKE 'confirmed-%' THEN s.media_emby_id END) supported FROM housekeeping_signal s WHERE s.run_id=@run AND s.candidate_external_id IS NOT NULL AND s.candidate_external_id<>coalesce(s.current_external_id,'') GROUP BY s.person_emby_id,s.provider,s.current_external_id,s.candidate_external_id), grouped AS (
SELECT person_emby_id,provider,current_external_id,group_concat(candidate_external_id) candidate_ids,max(linked) linked,max(checked) checked,sum(supported) supported FROM positives WHERE supported>0 GROUP BY person_emby_id,provider,current_external_id)
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,g.person_emby_id,'emby:'||g.person_emby_id,'change_identity','review-unresolved-provider-id','partial-alternative-support',g.provider,g.current_external_id,g.candidate_ids,g.linked,g.checked,g.supported,.62,upper(g.provider)||' found positive media evidence for alternative ID(s) '||g.candidate_ids||' on '||g.supported||' relationship(s), below a decisive replacement or partition threshold. Review the retained candidate evidence.',@now
FROM grouped g WHERE NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=g.person_emby_id AND h.provider=g.provider AND h.recommendation_type IN('replace-provider-id','review-merge'))",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
        }

        private static void UniversalAuditDecisions(IDatabaseConnection x,long run)=>Exec(x,@"INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,s.person_emby_id,s.subject_truth_entity_id,'change_identity','review-unresolved-provider-id',CASE s.signal_type WHEN 'identity-unsupported' THEN 'current-identity-not-on-media' WHEN 'identity-partially-supported' THEN 'current-identity-partial-media-conflict' WHEN 'identity-audit-missing' THEN 'missing-provider-identity' ELSE 'incomplete-media-coverage' END,s.provider,s.current_external_id,coalesce(s.linked_media_count,0),coalesce(s.checked_media_count,0),coalesce(s.supported_media_count,0),CASE s.signal_type WHEN 'identity-unsupported' THEN .30 WHEN 'identity-partially-supported' THEN .55 ELSE .35 END,s.evidence_text||'. The universal audit found insufficient or contradictory evidence; inspect retained candidates and relationship observations before changing the identity.',@now
FROM housekeeping_signal s WHERE s.run_id=@run AND s.signal_type IN('identity-unsupported','identity-partially-supported','identity-audit-missing','identity-audit-incomplete') AND coalesce(s.linked_media_count,0)>0 AND NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=s.person_emby_id AND h.provider=s.provider AND h.recommendation_type IN('replace-provider-id','review-merge','review-unresolved-provider-id'))",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void ProviderIssues(IDatabaseConnection x,long run)
        {
            Exec(x,@"WITH candidate_rows AS (
SELECT DISTINCT s.person_emby_id,s.provider,s.candidate_external_id id,s.candidate_name name,e.birth_date birth,CASE WHEN s.signal_type LIKE 'confirmed-%' OR p.tmdb_id=s.candidate_external_id THEN 1 ELSE 0 END anchored FROM housekeeping_signal s JOIN tmdb_entity e ON s.provider='tmdb' AND e.entity_type='person' AND e.tmdb_id=s.candidate_external_id JOIN emby_item p ON p.emby_id=s.person_emby_id WHERE s.run_id=@run AND s.candidate_external_id IS NOT NULL
UNION ALL SELECT DISTINCT s.person_emby_id,s.provider,s.candidate_external_id,s.candidate_name,e.birth_date,CASE WHEN s.signal_type LIKE 'confirmed-%' OR p.tvdb_id=s.candidate_external_id THEN 1 ELSE 0 END FROM housekeeping_signal s JOIN tvdb_entity e ON s.provider='tvdb' AND e.entity_type='person' AND e.tvdb_id=s.candidate_external_id JOIN emby_item p ON p.emby_id=s.person_emby_id WHERE s.run_id=@run AND s.candidate_external_id IS NOT NULL), candidate_people AS (
SELECT person_emby_id,provider,id,max(name) name,max(birth) birth,max(anchored) anchored FROM candidate_rows GROUP BY person_emby_id,provider,id), pairs AS (
SELECT a.person_emby_id,a.provider,CASE WHEN cast(a.id AS integer)<cast(b.id AS integer) THEN a.id||','||b.id ELSE b.id||','||a.id END ids,a.id id1,b.id id2,a.name name1,b.name name2,a.birth birth1,b.birth birth2,max(a.anchored,b.anchored) anchored
FROM candidate_people a JOIN candidate_people b ON b.person_emby_id=a.person_emby_id AND b.provider=a.provider AND b.id>a.id WHERE a.birth IS NOT NULL AND a.birth<>'' AND a.birth=b.birth AND (lower(replace(a.name,'.',''))=lower(replace(b.name,'.','')) OR lower(substr(a.name,1,instr(a.name||' ',' ')-1))=lower(substr(b.name,1,instr(b.name||' ',' ')-1))))
INSERT INTO provider_identity_issue(provider,issue_type,identity_ids,related_emby_ids,status,confidence,evidence_json,first_observed_utc,last_observed_utc)
SELECT provider,'person-split',ids,cast(person_emby_id AS text),'pending',.78,json_object('identity_1',id1,'name_1',name1,'identity_2',id2,'name_2',name2,'shared_birth_date',birth1,'reason','Compatible names and identical birth dates nominate a provider-side person split; linked-media evidence remains separately reviewable.'),@now,@now FROM pairs
WHERE anchored=1
AND (provider<>'tvdb' OR 2>(SELECT count(DISTINCT ra.source_name) FROM remote_id ra JOIN remote_id rb ON rb.entity_type='person' AND rb.tvdb_id=id2 AND rb.source_name=ra.source_name AND rb.remote_id<>ra.remote_id WHERE ra.entity_type='person' AND ra.tvdb_id=id1 AND ra.source_name IN('IMDB','TheMovieDB.com')))
AND (provider<>'tmdb' OR 2>(SELECT count(DISTINCT xa.source_name) FROM tmdb_external_id xa JOIN tmdb_external_id xb ON xb.entity_type='person' AND xb.tmdb_id=id2 AND xb.source_name=xa.source_name AND xb.external_id<>xa.external_id WHERE xa.entity_type='person' AND xa.tmdb_id=id1 AND xa.source_name IN('imdb','tvdb','wikidata')))
ON CONFLICT(provider,issue_type,identity_ids) DO UPDATE SET related_emby_ids=excluded.related_emby_ids,last_observed_utc=excluded.last_observed_utc,evidence_json=excluded.evidence_json,confidence=excluded.confidence",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});
        }

        private void Reacquire(string provider,long run,CancellationToken token,Action<string,double,TimeSpan> report,Stopwatch clock,double start,double endPercent)
        {
            long total=CountCandidates(provider),last=0,done=0;
            while(true){token.ThrowIfCancellationRequested();long end=NextEnd(provider,last);if(end==0)break;long batch=0;
                Tx(x=>{ReacquiredBatch(x,provider,run,last,end);batch=CountRange(x,provider,last,end);done+=batch;State(x,run,provider+"-reacquisition",start+(endPercent-start)*done/Math.Max(1d,total));});
                last=end;report?.Invoke(provider.ToUpperInvariant()+" reacquisition "+done+"/"+total,start+(endPercent-start)*done/Math.Max(1d,total),clock.Elapsed);}
        }

        private long CountCandidates(string p)=>Scalar(p=="tmdb"?"SELECT count(*) FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.provenance='inferred' AND r.resolved_tmdb_id IS NOT NULL AND coalesce(p.tmdb_id,'')<>r.resolved_tmdb_id":"SELECT count(*) FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.provenance='inferred' AND r.resolved_tvdb_id IS NOT NULL AND coalesce(p.tvdb_id,'')<>r.resolved_tvdb_id");
        private long NextEnd(string p,long last)=>Scalar(db,p=="tmdb"?"SELECT max(emby_id) FROM (SELECT p.emby_id FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.item_type='person' AND r.provenance='inferred' AND r.resolved_tmdb_id IS NOT NULL AND coalesce(p.tmdb_id,'')<>r.resolved_tmdb_id ORDER BY p.emby_id LIMIT 1000)":"SELECT max(emby_id) FROM (SELECT p.emby_id FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.item_type='person' AND r.provenance='inferred' AND r.resolved_tvdb_id IS NOT NULL AND coalesce(p.tvdb_id,'')<>r.resolved_tvdb_id ORDER BY p.emby_id LIMIT 1000)",s=>s.TryBind("@last",last));
        private static long CountRange(IDatabaseConnection x,string p,long last,long end)=>Scalar(x,p=="tmdb"?"SELECT count(*) FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.emby_id<=@end AND p.item_type='person' AND r.provenance='inferred' AND r.resolved_tmdb_id IS NOT NULL AND coalesce(p.tmdb_id,'')<>r.resolved_tmdb_id":"SELECT count(*) FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.emby_id<=@end AND p.item_type='person' AND r.provenance='inferred' AND r.resolved_tvdb_id IS NOT NULL AND coalesce(p.tvdb_id,'')<>r.resolved_tvdb_id",s=>{s.TryBind("@last",last);s.TryBind("@end",end);});

        private static void ReacquiredBatch(IDatabaseConnection x,string p,long run,long last,long end)
        {
            var sql=p=="tmdb"?@"WITH q AS (SELECT p.emby_id,p.tmdb_id old_id,r.resolved_tmdb_id new_id,r.evidence_json FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.emby_id<=@end AND p.item_type='person' AND r.resolved_tmdb_id IS NOT NULL AND coalesce(p.tmdb_id,'')<>r.resolved_tmdb_id),v AS (SELECT q.emby_id,count(DISTINCT er.media_emby_id) linked,count(DISTINCT CASE WHEN c.person_tmdb_id=q.new_id THEN er.media_emby_id END) supported FROM q LEFT JOIN emby_relationship er ON er.person_emby_id=q.emby_id LEFT JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id AND c.person_tmdb_id=q.new_id GROUP BY q.emby_id) INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc) SELECT @run,q.emby_id,'emby:'||q.emby_id,'change_identity','replace-provider-id','linked-media-identity','tmdb',q.old_id,q.new_id,v.linked,v.linked,v.supported,.90,coalesce(q.evidence_json,'TMDB replacement'),@now FROM q JOIN v ON v.emby_id=q.emby_id":@"WITH q AS (SELECT p.emby_id,p.tvdb_id old_id,r.resolved_tvdb_id new_id,r.evidence_json FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.emby_id>@last AND p.emby_id<=@end AND p.item_type='person' AND r.resolved_tvdb_id IS NOT NULL AND coalesce(p.tvdb_id,'')<>r.resolved_tvdb_id),v AS (SELECT q.emby_id,count(DISTINCT er.media_emby_id) linked,count(DISTINCT CASE WHEN c.person_tvdb_id=q.new_id THEN er.media_emby_id END) supported FROM q LEFT JOIN emby_relationship er ON er.person_emby_id=q.emby_id LEFT JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tvdb_credit_observation c ON c.production_tvdb_id=m.tvdb_id AND c.person_tvdb_id=q.new_id GROUP BY q.emby_id) INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc) SELECT @run,q.emby_id,'emby:'||q.emby_id,'change_identity','replace-provider-id','linked-media-identity','tvdb',q.old_id,q.new_id,v.linked,v.linked,v.supported,.88,coalesce(q.evidence_json,'TVDB replacement'),@now FROM q JOIN v ON v.emby_id=q.emby_id";
            if(p=="tmdb") sql=sql.Replace("r.evidence_json FROM","r.evidence_json,r.method FROM")
                .Replace("LEFT JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id","LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id LEFT JOIN tmdb_credit_observation c ON c.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id)")
                .Replace("v.linked,v.linked,v.supported,.90,coalesce","v.linked,CASE WHEN q.method='targeted-scope-aware-media-cast' THEN coalesce(json_extract(q.evidence_json,'$.checked_exact_scope_media'),v.linked) ELSE v.linked END,CASE WHEN q.method='targeted-scope-aware-media-cast' THEN coalesce(json_extract(q.evidence_json,'$.exact_scope_cast_matches'),0)+coalesce(json_extract(q.evidence_json,'$.broader_series_scope_episode_matches'),0) ELSE v.supported END,CASE WHEN q.method='targeted-scope-aware-media-cast' THEN coalesce(json_extract(q.evidence_json,'$.confidence'),.90) ELSE .90 END,coalesce");
            else sql=sql.Replace("r.evidence_json FROM","r.evidence_json,r.confidence resolution_confidence,r.method FROM")
                .Replace("v.supported,.88,coalesce","CASE WHEN q.method='targeted-scope-aware-media-cast' THEN coalesce(json_extract(q.evidence_json,'$.exact_scope_cast_matches'),0)+coalesce(json_extract(q.evidence_json,'$.broader_series_scope_episode_matches'),0) ELSE v.supported END,coalesce(q.resolution_confidence,.88),coalesce");
            sql=sql.Replace("WHERE p.emby_id>@last","WHERE r.provenance='inferred' AND p.emby_id>@last")
                .Replace("FROM q JOIN v ON v.emby_id=q.emby_id",p=="tmdb"?"FROM q JOIN v ON v.emby_id=q.emby_id JOIN tmdb_item_resolution rr ON rr.emby_id=q.emby_id WHERE v.supported>0 OR rr.method='targeted-scope-aware-media-cast'":"FROM q JOIN v ON v.emby_id=q.emby_id WHERE v.supported>0 OR q.method='targeted-scope-aware-media-cast'");
            Exec(x,sql,s=>{s.TryBind("@run",run);s.TryBind("@last",last);s.TryBind("@end",end);s.TryBind("@now",Now());});
        }

        private static void Unavailable(IDatabaseConnection x,long run)=>Exec(x,@"INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,linked_media_count,confidence,evidence_summary,created_utc) SELECT @run,p.emby_id,'emby:'||p.emby_id,'change_identity','remove-provider-id','identity-unavailable','tmdb',p.tmdb_id,(SELECT count(*) FROM emby_relationship e WHERE e.person_emby_id=p.emby_id),.80,'TMDB explicitly reports identity unavailable',@now FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.provenance='direct-unavailable' AND r.resolved_tmdb_id IS NULL UNION ALL SELECT @run,p.emby_id,'emby:'||p.emby_id,'change_identity','remove-provider-id','identity-unavailable','tvdb',p.tvdb_id,(SELECT count(*) FROM emby_relationship e WHERE e.person_emby_id=p.emby_id),.80,'TVDB explicitly reports identity unavailable',@now FROM emby_item p JOIN item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.provenance='direct-unavailable' AND r.resolved_tvdb_id IS NULL",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void UnavailableExplicit(IDatabaseConnection x,long run)=>Exec(x,@"WITH coverage AS (
SELECT person_emby_id,provider,count(DISTINCT media_emby_id) linked,sum(CASE WHEN signal_type='media-checked' THEN 1 ELSE 0 END) checked FROM housekeeping_signal WHERE run_id=@run AND signal_type IN('media-checked','media-unavailable','unchecked') GROUP BY person_emby_id,provider), positives AS (
SELECT person_emby_id,provider,sum(CASE WHEN signal_type LIKE 'confirmed-%' THEN 1 ELSE 0 END) supported FROM housekeeping_signal WHERE run_id=@run GROUP BY person_emby_id,provider)
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,c.person_emby_id,'emby:'||c.person_emby_id,'change_identity','remove-provider-id','identity-unavailable',c.provider,CASE c.provider WHEN 'tmdb' THEN p.tmdb_id ELSE p.tvdb_id END,c.linked,c.checked,0,.80,upper(c.provider)||' explicitly reports the assigned identity unavailable. All '||c.checked||' of '||c.linked||' linked media were resolved and checked; no compatible candidate was present. Candidate and relationship signals are retained for review.',@now
FROM coverage c JOIN emby_item p ON p.emby_id=c.person_emby_id LEFT JOIN positives q ON q.person_emby_id=c.person_emby_id AND q.provider=c.provider WHERE c.linked=c.checked AND coalesce(q.supported,0)=0 AND NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=c.person_emby_id AND h.provider=c.provider AND h.recommendation_type IN('replace-provider-id','review-merge','review-unresolved-provider-id'))",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void MediaBackedTmdbReplacements(IDatabaseConnection x,long run)=>Exec(x,@"WITH dead AS (
SELECT p.emby_id,p.name,p.tmdb_id,(SELECT count(*) FROM emby_relationship er WHERE er.person_emby_id=p.emby_id) linked,
 (SELECT count(DISTINCT er.media_emby_id) FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id WHERE er.person_emby_id=p.emby_id AND coalesce(m.tmdb_id,mr.resolved_tmdb_id) IS NOT NULL) checked
FROM emby_item p JOIN tmdb_item_resolution r ON r.emby_id=p.emby_id WHERE p.item_type='person' AND r.provenance='direct-unavailable'), candidates AS (
SELECT d.emby_id,d.name current_name,d.tmdb_id old_id,d.linked,d.checked,e.tmdb_id new_id,e.name candidate_name,count(DISTINCT er.media_emby_id) supported,
 CASE WHEN lower(e.name)=lower(d.name) OR EXISTS(SELECT 1 FROM tmdb_alias a WHERE a.entity_type='person' AND a.tmdb_id=e.tmdb_id AND lower(a.alias)=lower(d.name)) THEN 1 ELSE 0 END exact_or_alias
FROM dead d JOIN emby_relationship er ON er.person_emby_id=d.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) JOIN tmdb_entity e ON e.entity_type='person' AND e.tmdb_id=c.person_tmdb_id
WHERE e.tmdb_id<>d.tmdb_id AND (lower(e.name)=lower(d.name) OR EXISTS(SELECT 1 FROM tmdb_alias a WHERE a.entity_type='person' AND a.tmdb_id=e.tmdb_id AND lower(a.alias)=lower(d.name)) OR (substr(lower(e.name),1,1)=substr(lower(d.name),1,1) AND instr(e.name,' ')>0 AND instr(d.name,' ')>0 AND lower(substr(e.name,instr(e.name,' ')+1))=lower(substr(d.name,instr(d.name,' ')+1))))
GROUP BY d.emby_id,d.name,d.tmdb_id,d.linked,d.checked,e.tmdb_id,e.name), eligible AS (
SELECT c.* FROM candidates c WHERE (c.exact_or_alias=1 AND c.supported>0) OR (c.exact_or_alias=0 AND c.checked>=2 AND c.supported=c.checked)), winners AS (
SELECT e.* FROM eligible e WHERE e.supported=(SELECT max(x.supported) FROM eligible x WHERE x.emby_id=e.emby_id) AND 1=(SELECT count(*) FROM eligible x WHERE x.emby_id=e.emby_id AND x.supported=e.supported))
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,emby_id,'emby:'||emby_id,'change_identity','replace-provider-id','linked-media-identity','tmdb',old_id,new_id,linked,checked,supported,CASE WHEN exact_or_alias=1 THEN .97 WHEN supported=checked THEN .95 ELSE .88 END,
'Dead TMDB ID '||old_id||'; unique linked-media candidate '||candidate_name||' ('||new_id||') is credited on '||supported||' of '||checked||' TMDB-resolved linked media. Current Emby name remains '||current_name,@now FROM winners
WHERE NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=winners.emby_id AND h.provider='tmdb' AND h.recommendation_type='replace-provider-id')",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private sealed class RenameProviderEvidence
        {
            public string Provider; public string ExternalId; public string CanonicalName; public List<string> Aliases;
            public int Linked; public int Checked; public int Supported; public bool Collision;
        }

        private void RenamesV3(IDatabaseConnection x,long run)
        {
            const string sql=@"WITH audit AS (
SELECT person_emby_id,provider,max(linked_media_count) linked,max(checked_media_count) checked,max(supported_media_count) supported FROM housekeeping_signal WHERE run_id=@run AND signal_type IN('identity-supported','identity-partially-supported') GROUP BY person_emby_id,provider), known_names AS (SELECT lower(name) name,count(*) owners FROM emby_item WHERE item_type='person' AND name IS NOT NULL GROUP BY lower(name))
SELECT p.emby_id,p.name,
 p.tmdb_id,te.name,coalesce(ta.linked,0),coalesce(ta.checked,0),coalesce(ta.supported,0),(SELECT group_concat(alias,char(31)) FROM tmdb_alias WHERE entity_type='person' AND tmdb_id=p.tmdb_id),CASE WHEN coalesce(tk.owners,0)>CASE WHEN lower(p.name)=lower(te.name) THEN 1 ELSE 0 END THEN 1 ELSE 0 END,
 p.tvdb_id,ve.name,coalesce(va.linked,0),coalesce(va.checked,0),coalesce(va.supported,0),(SELECT group_concat(alias,char(31)) FROM tvdb_alias WHERE entity_type='person' AND tvdb_id=p.tvdb_id),CASE WHEN coalesce(vk.owners,0)>CASE WHEN lower(p.name)=lower(ve.name) THEN 1 ELSE 0 END THEN 1 ELSE 0 END
FROM emby_item p LEFT JOIN tmdb_entity te ON te.entity_type='person' AND te.tmdb_id=p.tmdb_id LEFT JOIN tvdb_entity ve ON ve.entity_type='person' AND ve.tvdb_id=p.tvdb_id LEFT JOIN audit ta ON ta.person_emby_id=p.emby_id AND ta.provider='tmdb' LEFT JOIN audit va ON va.person_emby_id=p.emby_id AND va.provider='tvdb' LEFT JOIN known_names tk ON tk.name=lower(te.name) LEFT JOIN known_names vk ON vk.name=lower(ve.name)
WHERE p.item_type='person' AND (coalesce(ta.supported,0)>0 OR coalesce(va.supported,0)>0)";
            using(var s=x.PrepareStatement(sql))
            {
                s.TryBind("@run",run);
                foreach(var row in s.ExecuteQuery())
                {
                    var embyId=row.GetInt64(0);var current=row.IsDBNull(1)?string.Empty:row.GetString(1);var providers=new List<RenameProviderEvidence>();
                    AddRenameProvider(providers,"tmdb",row,2,3,4,5,6,7,8);
                    AddRenameProvider(providers,"tvdb",row,9,10,11,12,13,14,15);
                    var healthy=providers.Where(p=>p.Supported>0&&!string.IsNullOrWhiteSpace(p.CanonicalName)).ToList();if(healthy.Count==0)continue;
                    if(healthy.Any(p=>ExactProviderName(p,current)))continue;
                    RenameProviderEvidence chosen;string provider;string consensus;
                    if(healthy.Count>1)
                    {
                        var forms=healthy.Select(p=>PersonNameCompatibility.ExactForm(p.CanonicalName)).Distinct().ToList();
                        if(forms.Count!=1)continue;
                        chosen=healthy.OrderByDescending(p=>p.Supported).ThenBy(p=>p.Provider=="tmdb"?0:1).First();provider="cross-provider";consensus="TMDB and TVDB agree on canonical name '"+chosen.CanonicalName+"'";
                    }
                    else {chosen=healthy[0];provider=chosen.Provider;consensus=chosen.Provider.ToUpperInvariant()+" supplies the only healthy media-backed canonical name";}
                    if(PersonNameCompatibility.ExactForm(current)==PersonNameCompatibility.ExactForm(chosen.CanonicalName))continue;
                    var match=PersonNameCompatibility.Compare(current,chosen.CanonicalName,healthy.SelectMany(p=>p.Aliases),Plugin.Instance.Configuration.GivenNameEquivalences);
                    var collision=healthy.Any(p=>p.Collision);var evidence=consensus+"; "+string.Join("; ",healthy.Select(p=>p.Provider.ToUpperInvariant()+" "+p.ExternalId+" supports "+p.Supported+"/"+p.Checked+" checked linked media"))+"; current/proposed compatibility: "+match.Reason+". Name compatibility corroborates this rename only and does not establish identity.";
                    Exec(x,"INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc) VALUES(@run,@emby,@subject,'update',@type,@signal,@provider,@current,@proposed,@linked,@checked,@supported,@confidence,@evidence,@now)",q=>{q.TryBind("@run",run);q.TryBind("@emby",embyId);q.TryBind("@subject","emby:"+embyId);q.TryBind("@type",collision?"review-existing-emby-person":"rename-person");q.TryBind("@signal",collision?"emby-name-collision":healthy.Count>1?"media-backed-provider-consensus-rename":"media-backed-provider-rename");q.TryBind("@provider",provider);q.TryBind("@current",current);q.TryBind("@proposed",chosen.CanonicalName);q.TryBind("@linked",healthy.Max(p=>p.Linked));q.TryBind("@checked",healthy.Max(p=>p.Checked));q.TryBind("@supported",healthy.Max(p=>p.Supported));q.TryBind("@confidence",collision?.65:healthy.Count>1?.94:(match.Compatible?.90:.82));q.TryBind("@evidence",evidence);q.TryBind("@now",Now());});
                }
            }
        }

        private static void AddRenameProvider(List<RenameProviderEvidence> target,string provider,IResultSet row,int id,int name,int linked,int checkedMedia,int supported,int aliases,int collision)
        {
            if(row.IsDBNull(id))return;target.Add(new RenameProviderEvidence{Provider=provider,ExternalId=row.GetString(id),CanonicalName=row.IsDBNull(name)?null:row.GetString(name),Linked=row.GetInt(linked),Checked=row.GetInt(checkedMedia),Supported=row.GetInt(supported),Aliases=(row.IsDBNull(aliases)?string.Empty:row.GetString(aliases)).Split(new[]{(char)31},StringSplitOptions.RemoveEmptyEntries).ToList(),Collision=row.GetInt(collision)>0});
        }

        private static bool ExactProviderName(RenameProviderEvidence provider,string current)
        {
            var form=PersonNameCompatibility.ExactForm(current);return form==PersonNameCompatibility.ExactForm(provider.CanonicalName)||provider.Aliases.Any(a=>form==PersonNameCompatibility.ExactForm(a));
        }

        private static void RenamesV2(IDatabaseConnection x,long run)=>Exec(x,@"WITH audit AS (
SELECT person_emby_id,provider,max(linked_media_count) linked,max(checked_media_count) checked,max(supported_media_count) supported FROM housekeeping_signal WHERE run_id=@run AND signal_type IN('identity-supported','identity-partially-supported') GROUP BY person_emby_id,provider), provider_names AS (
SELECT p.emby_id,'tmdb' provider,p.tmdb_id external_id,e.name provider_name,p.name current_name FROM emby_item p JOIN tmdb_entity e ON e.entity_type='person' AND e.tmdb_id=p.tmdb_id WHERE p.item_type='person'
UNION ALL SELECT p.emby_id,'tvdb',p.tvdb_id,e.name,p.name FROM emby_item p JOIN tvdb_entity e ON e.entity_type='person' AND e.tvdb_id=p.tvdb_id WHERE p.item_type='person'), name_agreement AS (
SELECT pn.emby_id,pn.provider FROM provider_names pn WHERE lower(pn.provider_name)=lower(pn.current_name)
UNION SELECT p.emby_id,'tmdb' FROM emby_item p JOIN tmdb_alias a ON a.entity_type='person' AND a.tmdb_id=p.tmdb_id AND lower(a.alias)=lower(p.name) WHERE p.item_type='person'
UNION SELECT p.emby_id,'tvdb' FROM emby_item p JOIN tvdb_alias a ON a.entity_type='person' AND a.tvdb_id=p.tvdb_id AND lower(a.alias)=lower(p.name) WHERE p.item_type='person'), anchored AS (
SELECT DISTINCT n.emby_id FROM name_agreement n JOIN audit a ON a.person_emby_id=n.emby_id AND a.provider=n.provider AND a.supported>0), known_names AS (
SELECT lower(name) normalized_name,count(*) owners FROM emby_item WHERE item_type='person' AND name IS NOT NULL GROUP BY lower(name)), candidates AS (
SELECT pn.*,a.linked,a.checked,a.supported,CASE WHEN coalesce(k.owners,0)>0 THEN 1 ELSE 0 END collision FROM provider_names pn JOIN audit a ON a.person_emby_id=pn.emby_id AND a.provider=pn.provider AND a.supported>0 LEFT JOIN anchored z ON z.emby_id=pn.emby_id LEFT JOIN known_names k ON k.normalized_name=lower(pn.provider_name) WHERE z.emby_id IS NULL AND pn.provider_name IS NOT NULL AND lower(pn.provider_name)<>lower(pn.current_name))
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,emby_id,'emby:'||emby_id,'update',CASE WHEN collision=1 THEN 'review-existing-emby-person' ELSE 'rename-person' END,CASE WHEN collision=1 THEN 'emby-name-collision' ELSE 'media-backed-provider-rename' END,provider,current_name,provider_name,linked,checked,supported,CASE provider WHEN 'tmdb' THEN CASE collision WHEN 1 THEN .65 ELSE .90 END ELSE CASE collision WHEN 1 THEN .60 ELSE .86 END END,'Current name is not confirmed by any healthy media-backed provider identity; '||upper(provider)||' proposed name is backed by '||supported||' linked credit(s)',@now FROM candidates",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void Renames(IDatabaseConnection x,long run)=>Exec(x,@"WITH anchored_name AS (
SELECT p.emby_id FROM emby_item p WHERE p.item_type='person' AND (
 (p.tmdb_id IS NOT NULL AND (EXISTS(SELECT 1 FROM tmdb_entity e WHERE e.entity_type='person' AND e.tmdb_id=p.tmdb_id AND lower(e.name)=lower(p.name)) OR EXISTS(SELECT 1 FROM tmdb_alias a WHERE a.entity_type='person' AND a.tmdb_id=p.tmdb_id AND lower(a.alias)=lower(p.name))) AND EXISTS(SELECT 1 FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id AND c.person_tmdb_id=p.tmdb_id WHERE er.person_emby_id=p.emby_id))
 OR
 (p.tvdb_id IS NOT NULL AND (EXISTS(SELECT 1 FROM tvdb_entity e WHERE e.entity_type='person' AND e.tvdb_id=p.tvdb_id AND lower(e.name)=lower(p.name)) OR EXISTS(SELECT 1 FROM tvdb_alias a WHERE a.entity_type='person' AND a.tvdb_id=p.tvdb_id AND lower(a.alias)=lower(p.name))) AND EXISTS(SELECT 1 FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=m.tvdb_id AND c.person_tvdb_id=p.tvdb_id WHERE er.person_emby_id=p.emby_id))
))
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,p.emby_id,'emby:'||p.emby_id,'update',CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tmdb_name)) THEN 'review-existing-emby-person' ELSE 'rename-person' END,CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tmdb_name)) THEN 'emby-name-collision' ELSE 'media-backed-provider-rename' END,'tmdb',p.name,v.tmdb_name,
(SELECT count(*) FROM emby_relationship e WHERE e.person_emby_id=p.emby_id),(SELECT count(*) FROM emby_relationship e JOIN emby_item m ON m.emby_id=e.media_emby_id WHERE e.person_emby_id=p.emby_id AND m.tmdb_id IS NOT NULL),(SELECT count(DISTINCT e.media_emby_id) FROM emby_relationship e JOIN emby_item m ON m.emby_id=e.media_emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id AND c.person_tmdb_id=p.tmdb_id WHERE e.person_emby_id=p.emby_id),CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tmdb_name)) THEN .65 ELSE .90 END,'Current name is not confirmed by any healthy media-backed provider identity; TMDB proposed name is backed by linked credits',@now
FROM emby_item p JOIN provider_identity_signals v ON v.emby_id=p.emby_id WHERE p.item_type='person' AND NOT EXISTS(SELECT 1 FROM anchored_name a WHERE a.emby_id=p.emby_id) AND v.tmdb_provenance='direct' AND v.resolved_tmdb_id=p.tmdb_id AND v.tmdb_name IS NOT NULL AND lower(v.tmdb_name)<>lower(p.name) AND EXISTS(SELECT 1 FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id AND c.person_tmdb_id=p.tmdb_id WHERE er.person_emby_id=p.emby_id)
UNION ALL
SELECT @run,p.emby_id,'emby:'||p.emby_id,'update',CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tvdb_name)) THEN 'review-existing-emby-person' ELSE 'rename-person' END,CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tvdb_name)) THEN 'emby-name-collision' ELSE 'media-backed-provider-rename' END,'tvdb',p.name,v.tvdb_name,
(SELECT count(*) FROM emby_relationship e WHERE e.person_emby_id=p.emby_id),(SELECT count(*) FROM emby_relationship e JOIN emby_item m ON m.emby_id=e.media_emby_id WHERE e.person_emby_id=p.emby_id AND m.tvdb_id IS NOT NULL),(SELECT count(DISTINCT e.media_emby_id) FROM emby_relationship e JOIN emby_item m ON m.emby_id=e.media_emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=m.tvdb_id AND c.person_tvdb_id=p.tvdb_id WHERE e.person_emby_id=p.emby_id),CASE WHEN EXISTS(SELECT 1 FROM emby_item d WHERE d.item_type='person' AND d.emby_id<>p.emby_id AND lower(d.name)=lower(v.tvdb_name)) THEN .60 ELSE .86 END,'Current name is not confirmed by any healthy media-backed provider identity; TVDB proposed name is backed by linked credits',@now
FROM emby_item p JOIN provider_identity_signals v ON v.emby_id=p.emby_id WHERE p.item_type='person' AND NOT EXISTS(SELECT 1 FROM anchored_name a WHERE a.emby_id=p.emby_id) AND v.tvdb_provenance='direct' AND v.resolved_tvdb_id=p.tvdb_id AND v.tvdb_name IS NOT NULL AND lower(v.tvdb_name)<>lower(p.name) AND EXISTS(SELECT 1 FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=m.tvdb_id AND c.person_tvdb_id=p.tvdb_id WHERE er.person_emby_id=p.emby_id)",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void Merges(IDatabaseConnection x,long run)=>Exec(x,@"WITH identities AS (
SELECT 'tmdb' provider,tmdb_id external_id,emby_id FROM emby_item WHERE item_type='person' AND tmdb_id IS NOT NULL
UNION ALL SELECT 'tvdb',tvdb_id,emby_id FROM emby_item WHERE item_type='person' AND tvdb_id IS NOT NULL), duplicates AS (
SELECT provider,external_id FROM identities GROUP BY provider,external_id HAVING count(*)>1),
support AS (
SELECT i.provider,i.external_id,i.emby_id,
 (SELECT count(*) FROM emby_relationship er WHERE er.person_emby_id=i.emby_id) linked,
 (SELECT count(DISTINCT er.media_emby_id) FROM emby_relationship er JOIN emby_item m ON m.emby_id=er.media_emby_id
  WHERE er.person_emby_id=i.emby_id AND ((i.provider='tmdb' AND EXISTS(SELECT 1 FROM tmdb_credit_observation tc WHERE tc.production_tmdb_id=m.tmdb_id AND tc.person_tmdb_id=i.external_id))
   OR (i.provider='tvdb' AND EXISTS(SELECT 1 FROM tvdb_credit_observation vc WHERE vc.production_tvdb_id=m.tvdb_id AND vc.person_tvdb_id=i.external_id)))) supported
FROM identities i JOIN duplicates d ON d.provider=i.provider AND d.external_id=i.external_id), candidates AS (
SELECT provider,external_id,min(emby_id) survivor,group_concat(emby_id) participants,sum(linked) linked,sum(supported) supported,count(*) people,
 sum(CASE WHEN supported>0 THEN 1 ELSE 0 END) supported_people FROM support GROUP BY provider,external_id HAVING count(*)>1)
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,survivor,'emby:'||survivor,'merge','review-merge','shared-provider-identity',provider,participants,external_id,linked,linked,supported,.85,
'Shared '||upper(provider)||' ID '||external_id||' is provider-credit-backed for all '||people||' Emby people; choose and lock a survivor only after reviewing identities and every linked credit',@now
FROM candidates WHERE supported_people=people",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void SplitsV2(IDatabaseConnection x,long run)=>Exec(x,@"WITH candidate_media AS (
SELECT person_emby_id,provider,current_external_id,candidate_external_id,media_emby_id FROM housekeeping_signal WHERE run_id=@run AND signal_type IN('confirmed-exact-scope','confirmed-broader-series-scope') AND candidate_external_id IS NOT NULL), candidate_people AS (
SELECT DISTINCT person_emby_id,provider FROM candidate_media), current_media AS (
SELECT p.emby_id person_emby_id,'tmdb' provider,p.tmdb_id current_id,er.media_emby_id FROM candidate_people q JOIN emby_item p ON p.emby_id=q.person_emby_id AND q.provider='tmdb' JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND c.production_type=m.item_type AND c.person_tmdb_id=p.tmdb_id
UNION ALL SELECT p.emby_id,'tvdb',p.tvdb_id,er.media_emby_id FROM candidate_people q JOIN emby_item p ON p.emby_id=q.person_emby_id AND q.provider='tvdb' JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND c.production_type=m.item_type AND c.person_tvdb_id=p.tvdb_id), candidate_stats AS (
SELECT person_emby_id,provider,current_external_id current_id,candidate_external_id candidate_id,count(DISTINCT media_emby_id) candidate_media FROM candidate_media WHERE candidate_external_id<>coalesce(current_external_id,'') GROUP BY person_emby_id,provider,current_external_id,candidate_external_id), current_stats AS (
SELECT person_emby_id,provider,current_id,count(DISTINCT media_emby_id) current_media FROM current_media GROUP BY person_emby_id,provider,current_id), shared_stats AS (
SELECT c.person_emby_id,c.provider,c.candidate_external_id candidate_id,count(DISTINCT c.media_emby_id) shared_media FROM candidate_media c JOIN current_media m ON m.person_emby_id=c.person_emby_id AND m.provider=c.provider AND m.media_emby_id=c.media_emby_id WHERE c.candidate_external_id<>coalesce(c.current_external_id,'') GROUP BY c.person_emby_id,c.provider,c.candidate_external_id), partitions AS (
SELECT c.person_emby_id,c.provider,c.current_id,c.candidate_id,c.candidate_media,m.current_media,coalesce(s.shared_media,0) shared_media FROM candidate_stats c JOIN current_stats m ON m.person_emby_id=c.person_emby_id AND m.provider=c.provider LEFT JOIN shared_stats s ON s.person_emby_id=c.person_emby_id AND s.provider=c.provider AND s.candidate_id=c.candidate_id WHERE c.candidate_media>0 AND m.current_media>0 AND coalesce(s.shared_media,0)=0), grouped AS (
SELECT person_emby_id,provider,current_id,group_concat(candidate_id) ids,sum(candidate_media) candidate_media,max(current_media) current_media FROM partitions GROUP BY person_emby_id,provider,current_id)
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,g.person_emby_id,'emby:'||g.person_emby_id,'split','review-split','linked-media-partition',g.provider,g.current_id,g.ids,(SELECT count(DISTINCT media_emby_id) FROM emby_relationship er WHERE er.person_emby_id=g.person_emby_id),g.current_media+g.candidate_media,g.current_media+g.candidate_media,.88,'Emby person '||g.person_emby_id||' has disjoint linked-media support for current '||upper(g.provider)||' ID '||coalesce(g.current_id,'-')||' and candidate ID(s) '||g.ids||'; review relationship partition and existing Emby ownership before creating a person',@now FROM grouped g
WHERE NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=g.person_emby_id AND h.recommendation_type='review-split' AND h.provider=g.provider)",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void Splits(IDatabaseConnection x,long run)=>Exec(x,@"WITH s AS (SELECT p.emby_id,'tmdb' provider,p.tmdb_id current_id,cp.tmdb_id candidate,count(DISTINCT er.media_emby_id) media FROM emby_item p JOIN emby_item cp ON cp.item_type='person' AND cp.emby_id<>p.emby_id AND cp.name=p.name AND cp.tmdb_id IS NOT NULL JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=m.tmdb_id AND c.person_tmdb_id=cp.tmdb_id WHERE p.item_type='person' GROUP BY p.emby_id,p.tmdb_id,cp.tmdb_id UNION ALL SELECT p.emby_id,'tvdb',p.tvdb_id,cp.tvdb_id,count(DISTINCT er.media_emby_id) FROM emby_item p JOIN emby_item cp ON cp.item_type='person' AND cp.emby_id<>p.emby_id AND cp.name=p.name AND cp.tvdb_id IS NOT NULL JOIN emby_relationship er ON er.person_emby_id=p.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=m.tvdb_id AND c.person_tvdb_id=cp.tvdb_id WHERE p.item_type='person' GROUP BY p.emby_id,p.tvdb_id,cp.tvdb_id),q AS(SELECT emby_id,provider,current_id,count(*) n,sum(media) media,group_concat(candidate) ids FROM s GROUP BY emby_id,provider,current_id HAVING count(*)>1) INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,supported_media_count,confidence,evidence_summary,created_utc) SELECT @run,emby_id,'emby:'||emby_id,'split','review-split','linked-media-partition',provider,current_id,ids,media,.75,'Emby person '||emby_id||' has linked credits partitioned across multiple name-compatible '||upper(provider)||' identities; review each media relationship before creating or moving people',@now FROM q",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void CrossProviderSplits(IDatabaseConnection x,long run)=>Exec(x,@"WITH identities AS (
SELECT p.emby_id,p.name,p.tmdb_id,p.tvdb_id,p.imdb_id,te.name tmdb_name,json_extract(te.raw_json,'$.external_ids.imdb_id') tmdb_imdb,rt.remote_id tvdb_tmdb,ri.remote_id tvdb_imdb,(SELECT s.candidate_external_id FROM housekeeping_signal s JOIN remote_id ct ON ct.entity_type='person' AND ct.tvdb_id=s.candidate_external_id AND ct.source_name='TheMovieDB.com' AND ct.remote_id=p.tmdb_id JOIN remote_id ci ON ci.entity_type='person' AND ci.tvdb_id=s.candidate_external_id AND ci.source_name='IMDB' AND ci.remote_id=coalesce(p.imdb_id,json_extract(te.raw_json,'$.external_ids.imdb_id')) WHERE s.run_id=@run AND s.person_emby_id=p.emby_id AND s.provider='tvdb' AND s.signal_type LIKE 'confirmed-%' GROUP BY s.candidate_external_id ORDER BY count(DISTINCT s.media_emby_id) DESC LIMIT 1) retain_tvdb
FROM emby_item p JOIN tmdb_entity te ON te.entity_type='person' AND te.tmdb_id=p.tmdb_id JOIN tvdb_entity ve ON ve.entity_type='person' AND ve.tvdb_id=p.tvdb_id JOIN remote_id rt ON rt.entity_type='person' AND rt.tvdb_id=p.tvdb_id AND rt.source_name='TheMovieDB.com' AND rt.remote_id<>p.tmdb_id JOIN remote_id ri ON ri.entity_type='person' AND ri.tvdb_id=p.tvdb_id AND ri.source_name='IMDB' AND ri.remote_id<>coalesce(p.imdb_id,json_extract(te.raw_json,'$.external_ids.imdb_id')) WHERE p.item_type='person' AND p.tmdb_id IS NOT NULL AND p.tvdb_id IS NOT NULL), tmdb_supported AS (
SELECT DISTINCT i.emby_id,er.media_emby_id FROM identities i JOIN emby_relationship er ON er.person_emby_id=i.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id JOIN tmdb_credit_observation c ON c.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND c.production_type=m.item_type AND c.person_tmdb_id=i.tmdb_id), tvdb_supported AS (
SELECT DISTINCT i.emby_id,er.media_emby_id FROM identities i JOIN emby_relationship er ON er.person_emby_id=i.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id JOIN tvdb_credit_observation c ON c.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND c.production_type=m.item_type AND c.person_tvdb_id=i.tvdb_id), tmdb_stats AS (
SELECT emby_id,count(*) media FROM tmdb_supported GROUP BY emby_id), tvdb_stats AS (
SELECT emby_id,count(*) media FROM tvdb_supported GROUP BY emby_id), shared_stats AS (
SELECT t.emby_id,count(*) media FROM tmdb_supported t JOIN tvdb_supported v ON v.emby_id=t.emby_id AND v.media_emby_id=t.media_emby_id GROUP BY t.emby_id), linked_stats AS (
SELECT i.emby_id,count(DISTINCT er.media_emby_id) media FROM identities i JOIN emby_relationship er ON er.person_emby_id=i.emby_id GROUP BY i.emby_id), support AS (
SELECT i.*,coalesce(t.media,0) tmdb_media,coalesce(v.media,0) tvdb_media,coalesce(s.media,0) shared_media,coalesce(l.media,0) linked,(SELECT group_concat(m.name,', ') FROM tmdb_supported z JOIN emby_item m ON m.emby_id=z.media_emby_id WHERE z.emby_id=i.emby_id) tmdb_titles,(SELECT group_concat(m.name,', ') FROM tvdb_supported z JOIN emby_item m ON m.emby_id=z.media_emby_id WHERE z.emby_id=i.emby_id) tvdb_titles FROM identities i LEFT JOIN tmdb_stats t ON t.emby_id=i.emby_id LEFT JOIN tvdb_stats v ON v.emby_id=i.emby_id LEFT JOIN shared_stats s ON s.emby_id=i.emby_id LEFT JOIN linked_stats l ON l.emby_id=i.emby_id), eligible AS (
SELECT * FROM support WHERE tvdb_tmdb IS NOT NULL AND tvdb_tmdb<>tmdb_id AND tvdb_imdb IS NOT NULL AND coalesce(imdb_id,tmdb_imdb,'')<>'' AND tvdb_imdb<>coalesce(imdb_id,tmdb_imdb) AND tmdb_media>0 AND tvdb_media>0 AND shared_media=0)
INSERT INTO housekeeping_recommendation(run_id,person_emby_id,subject_truth_entity_id,operation,recommendation_type,primary_signal_type,provider,current_value,proposed_value,linked_media_count,checked_media_count,supported_media_count,confidence,evidence_summary,created_utc)
SELECT @run,emby_id,'emby:'||emby_id,'split','review-split','cross-provider-media-partition','cross-provider','TMDB='||tmdb_id||'; TVDB='||tvdb_id||'; IMDb='||coalesce(imdb_id,tmdb_imdb,'-'),json_object('retain_tmdb',tmdb_id,'retain_tvdb',retain_tvdb,'retain_imdb',coalesce(imdb_id,tmdb_imdb),'split_tmdb',tvdb_tmdb,'split_tvdb',tvdb_id,'split_imdb',tvdb_imdb),linked,tmdb_media+tvdb_media,tmdb_media+tvdb_media,.97,
'Actionable identity/media partition for Emby '||emby_id||' '||name||'. Retain cluster: TMDB '||tmdb_id||' / TVDB '||coalesce(retain_tvdb,'-')||' / IMDb '||coalesce(imdb_id,tmdb_imdb,'-')||' on ['||coalesce(tmdb_titles,'')||']. Create a new Emby person and move ['||coalesce(tvdb_titles,'')||'] to split cluster: TMDB '||tvdb_tmdb||' / TVDB '||tvdb_id||' / IMDb '||tvdb_imdb||'. Provider-native supported media are disjoint; shared supported media='||shared_media||'. The reviewer chooses the survivor if library context requires a different disposition.',@now FROM eligible
WHERE NOT EXISTS(SELECT 1 FROM housekeeping_recommendation h WHERE h.run_id=@run AND h.person_emby_id=eligible.emby_id AND h.recommendation_type='review-split' AND h.primary_signal_type='cross-provider-media-partition')",s=>{s.TryBind("@run",run);s.TryBind("@now",Now());});

        private static void ConsolidateReviewCases(IDatabaseConnection x,long run)
        {
            Exec(x,@"WITH collision_merge AS (
SELECT r.recommendation_id,r.person_emby_id source_id,o.emby_id owner_id,p.tmdb_id identity_id,p.name source_name,o.name owner_name,m.name media_name
FROM housekeeping_recommendation r JOIN emby_item p ON p.emby_id=r.person_emby_id JOIN emby_item o ON o.item_type='person' AND o.emby_id<>p.emby_id AND lower(o.name)=lower(r.proposed_value) JOIN emby_relationship er ON er.person_emby_id=o.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN tmdb_item_resolution mr ON mr.emby_id=m.emby_id JOIN tmdb_credit_observation c ON r.provider='tmdb' AND c.production_tmdb_id=coalesce(m.tmdb_id,mr.resolved_tmdb_id) AND c.production_type=m.item_type AND c.person_tmdb_id=p.tmdb_id
WHERE r.run_id=@run AND r.recommendation_type='review-existing-emby-person' AND p.tmdb_id IS NOT NULL
UNION ALL
SELECT r.recommendation_id,r.person_emby_id,o.emby_id,p.tvdb_id,p.name,o.name,m.name
FROM housekeeping_recommendation r JOIN emby_item p ON p.emby_id=r.person_emby_id JOIN emby_item o ON o.item_type='person' AND o.emby_id<>p.emby_id AND lower(o.name)=lower(r.proposed_value) JOIN emby_relationship er ON er.person_emby_id=o.emby_id JOIN emby_item m ON m.emby_id=er.media_emby_id LEFT JOIN item_resolution mr ON mr.emby_id=m.emby_id JOIN tvdb_credit_observation c ON r.provider='tvdb' AND c.production_tvdb_id=coalesce(m.tvdb_id,mr.resolved_tvdb_id) AND c.production_type=m.item_type AND c.person_tvdb_id=p.tvdb_id
WHERE r.run_id=@run AND r.recommendation_type='review-existing-emby-person' AND p.tvdb_id IS NOT NULL)
UPDATE housekeeping_recommendation SET person_emby_id=(SELECT min(source_id,owner_id) FROM collision_merge WHERE recommendation_id=housekeeping_recommendation.recommendation_id),subject_truth_entity_id='emby:'||(SELECT min(source_id,owner_id) FROM collision_merge WHERE recommendation_id=housekeeping_recommendation.recommendation_id),operation='merge',recommendation_type='review-merge',primary_signal_type='cross-emby-exact-media-identity',current_value=(SELECT CASE WHEN source_id<owner_id THEN source_id||','||owner_id ELSE owner_id||','||source_id END FROM collision_merge WHERE recommendation_id=housekeeping_recommendation.recommendation_id),proposed_value=(SELECT identity_id FROM collision_merge WHERE recommendation_id=housekeeping_recommendation.recommendation_id),confidence=.92,evidence_summary=(SELECT 'Review merge Emby '||source_id||' '||source_name||' and Emby '||owner_id||' '||owner_name||'. The healthy '||upper(housekeeping_recommendation.provider)||' identity '||identity_id||' proposes the existing canonical name and has exact provider-native support on media linked to the other Emby record: '||media_name||'. Show both people, all identities and all linked media before choosing a survivor.' FROM collision_merge WHERE recommendation_id=housekeeping_recommendation.recommendation_id) WHERE recommendation_id IN(SELECT recommendation_id FROM collision_merge)",s=>s.TryBind("@run",run));
            Exec(x,@"WITH candidate_stats AS (
SELECT person_emby_id,provider,current_external_id,candidate_external_id,count(DISTINCT media_emby_id) linked,count(DISTINCT CASE WHEN signal_type IN('confirmed-exact-scope','confirmed-broader-series-scope','not-present') THEN media_emby_id END) checked,count(DISTINCT CASE WHEN signal_type LIKE 'confirmed-%' THEN media_emby_id END) supported FROM housekeeping_signal WHERE run_id=@run AND media_emby_id IS NOT NULL GROUP BY person_emby_id,provider,current_external_id,candidate_external_id), strong AS (
SELECT r.recommendation_id,r.person_emby_id,r.current_value,r.proposed_value,c.linked,c.checked,c.supported,cur.supported current_supported,p.name,p.tmdb_id,coalesce(p.imdb_id,tx.external_id) imdb_id,
(SELECT group_concat(m.name,', ') FROM housekeeping_signal s JOIN emby_item m ON m.emby_id=s.media_emby_id WHERE s.run_id=@run AND s.person_emby_id=r.person_emby_id AND s.provider='tvdb' AND s.candidate_external_id=r.current_value AND s.signal_type LIKE 'confirmed-%') outlier_titles
FROM housekeeping_recommendation r JOIN candidate_stats c ON c.person_emby_id=r.person_emby_id AND c.provider='tvdb' AND c.candidate_external_id=r.proposed_value LEFT JOIN candidate_stats cur ON cur.person_emby_id=r.person_emby_id AND cur.provider='tvdb' AND cur.candidate_external_id=r.current_value JOIN emby_item p ON p.emby_id=r.person_emby_id LEFT JOIN tmdb_external_id tx ON tx.entity_type='person' AND tx.tmdb_id=p.tmdb_id AND tx.source_name='imdb' JOIN remote_id nt ON nt.entity_type='person' AND nt.tvdb_id=r.proposed_value AND nt.source_name='TheMovieDB.com' AND nt.remote_id=p.tmdb_id JOIN remote_id ni ON ni.entity_type='person' AND ni.tvdb_id=r.proposed_value AND ni.source_name='IMDB' AND ni.remote_id=coalesce(p.imdb_id,tx.external_id) JOIN remote_id ot ON ot.entity_type='person' AND ot.tvdb_id=r.current_value AND ot.source_name='TheMovieDB.com' AND ot.remote_id<>p.tmdb_id JOIN remote_id oi ON oi.entity_type='person' AND oi.tvdb_id=r.current_value AND oi.source_name='IMDB' AND oi.remote_id<>coalesce(p.imdb_id,tx.external_id) JOIN emby_item owner ON owner.item_type='person' AND owner.emby_id<>p.emby_id AND owner.tvdb_id=r.current_value AND owner.tmdb_id=ot.remote_id AND coalesce(owner.imdb_id,oi.remote_id)=oi.remote_id
WHERE r.run_id=@run AND r.recommendation_type='replace-provider-id' AND r.provider='tvdb' AND c.supported>=cast((c.linked*8+9)/10 AS integer) AND coalesce(cur.supported,0)<=1)
UPDATE housekeeping_recommendation SET primary_signal_type='provider-credit-misattribution',linked_media_count=(SELECT linked FROM strong WHERE recommendation_id=housekeeping_recommendation.recommendation_id),checked_media_count=(SELECT checked FROM strong WHERE recommendation_id=housekeeping_recommendation.recommendation_id),supported_media_count=(SELECT supported FROM strong WHERE recommendation_id=housekeeping_recommendation.recommendation_id),evidence_summary=(SELECT 'Replace TVDB '||current_value||' with '||proposed_value||' for Emby '||person_emby_id||' '||name||'. Candidate TVDB identity matches healthy TMDB '||tmdb_id||' / IMDb '||imdb_id||' and has exact provider-native support on '||supported||'/'||linked||' linked media. Current TVDB identity supports only '||current_supported||'/'||linked||' and belongs to a separately coherent Emby person; its isolated credit on ['||coalesce(outlier_titles,'')||'] is retained as likely provider-credit misattribution evidence, not split or merge evidence.' FROM strong WHERE recommendation_id=housekeeping_recommendation.recommendation_id) WHERE recommendation_id IN(SELECT recommendation_id FROM strong)",s=>s.TryBind("@run",run));

            Exec(x,@"DELETE FROM housekeeping_recommendation AS r WHERE r.run_id=@run AND r.recommendation_type='review-split' AND r.provider<>'cross-provider' AND EXISTS(SELECT 1 FROM housekeeping_recommendation a WHERE a.run_id=r.run_id AND a.person_emby_id=r.person_emby_id AND (a.primary_signal_type='cross-provider-media-partition' OR (a.recommendation_type='replace-provider-id' AND a.provider=r.provider)))",s=>s.TryBind("@run",run));
            Exec(x,@"DELETE FROM housekeeping_recommendation AS r WHERE r.run_id=@run AND r.recommendation_type='review-unresolved-provider-id' AND EXISTS(SELECT 1 FROM housekeeping_recommendation a WHERE a.run_id=r.run_id AND a.person_emby_id=r.person_emby_id AND (a.provider=r.provider OR a.provider='cross-provider') AND a.recommendation_type IN('replace-provider-id','review-merge','review-split'))",s=>s.TryBind("@run",run));
            Exec(x,@"DELETE FROM housekeeping_recommendation AS m WHERE m.run_id=@run AND m.recommendation_type='review-merge' AND EXISTS(SELECT 1 FROM housekeeping_recommendation r WHERE r.run_id=m.run_id AND r.recommendation_type='replace-provider-id' AND r.provider=m.provider AND r.current_value=m.proposed_value AND (','||m.current_value||',') LIKE '%,'||r.person_emby_id||',%')",s=>s.TryBind("@run",run));
            Exec(x,@"DELETE FROM housekeeping_recommendation WHERE run_id=@run AND recommendation_type='provider-person-split-error'",s=>s.TryBind("@run",run));
        }

        private static void DeltaTruth(IDatabaseConnection x,long run){Exec(x,"INSERT INTO truth(name,parent_truth_id,created_utc,status,description) VALUES(@name,1,@now,'frozen',@description)",s=>{s.TryBind("@name","Person housekeeping delta run "+run);s.TryBind("@now",Now());s.TryBind("@description","Delta truth from normalized-v9 run "+run);});long truth=LastId(x);Exec(x,"INSERT OR REPLACE INTO truth_entity_delta SELECT @truth,subject_truth_entity_id,'update',proposed_value,'update','housekeeping-run:'||@run FROM housekeeping_recommendation WHERE run_id=@run AND recommendation_type='rename-person' ORDER BY CASE provider WHEN 'tmdb' THEN 1 ELSE 0 END",s=>{s.TryBind("@truth",truth);s.TryBind("@run",run);});Exec(x,"INSERT OR REPLACE INTO truth_identity_delta SELECT @truth,subject_truth_entity_id,provider,CASE recommendation_type WHEN 'remove-provider-id' THEN 'remove' ELSE 'set' END,proposed_value,'housekeeping-run:'||@run FROM housekeeping_recommendation WHERE run_id=@run AND recommendation_type IN('remove-provider-id','replace-provider-id') ORDER BY confidence",s=>{s.TryBind("@truth",truth);s.TryBind("@run",run);});Exec(x,"UPDATE housekeeping_run SET derived_truth_id=@truth,phase='delta-truth',progress=96,heartbeat_utc=@now WHERE run_id=@run",s=>{s.TryBind("@truth",truth);s.TryBind("@now",Now());s.TryBind("@run",run);});}
        private static void Complete(IDatabaseConnection x,long run){var now=Now();Exec(x,"INSERT INTO experiment_metric SELECT @run,'person',recommendation_type,'recommendation_count',count(*) FROM housekeeping_recommendation WHERE run_id=@run GROUP BY recommendation_type",s=>s.TryBind("@run",run));Exec(x,"UPDATE housekeeping_run SET phase='completed',progress=100,status='completed',heartbeat_utc=@now,completed_utc=@now WHERE run_id=@run",s=>{s.TryBind("@now",now);s.TryBind("@run",run);});Exec(x,"UPDATE experiment_run SET status='completed',completed_utc=@now WHERE run_id=@run",s=>{s.TryBind("@now",now);s.TryBind("@run",run);});}
        private void Stop(long run,string status,string error){try{Tx(x=>{Exec(x,"UPDATE housekeeping_run SET status=@s,phase=@s,heartbeat_utc=@now,completed_utc=@now,error=@e WHERE run_id=@run",q=>{q.TryBind("@s",status);q.TryBind("@now",Now());q.TryBind("@e",error);q.TryBind("@run",run);});Exec(x,"UPDATE experiment_run SET status=@s,completed_utc=@now WHERE run_id=@run",q=>{q.TryBind("@s",status);q.TryBind("@now",Now());q.TryBind("@run",run);});});}catch{}}

        public List<HousekeepingResultRow> LatestResults(){var a=new List<HousekeepingResultRow>();const string sql=@"WITH RECURSIVE base AS (
SELECT r.*,CASE WHEN r.recommendation_type='review-merge' THEN CASE WHEN instr(r.proposed_value,',')>0 THEN r.proposed_value ELSE r.current_value END ELSE cast(r.person_emby_id AS text) END participant_ids
FROM housekeeping_latest_results r), parts(recommendation_id,rest,person_id) AS (
SELECT recommendation_id,participant_ids||',','' FROM base
UNION ALL SELECT recommendation_id,substr(rest,instr(rest,',')+1),substr(rest,1,instr(rest,',')-1) FROM parts WHERE rest<>''), participants AS (
SELECT recommendation_id,cast(person_id AS integer) person_id FROM parts WHERE person_id<>''), identity_agg AS (
SELECT p.recommendation_id,
 group_concat('Emby '||e.emby_id||': '||e.name,' | ') names,
 group_concat('Emby '||e.emby_id||': '||coalesce(e.tmdb_id,'-'),' | ') tmdb_ids,
 group_concat('Emby '||e.emby_id||': '||coalesce(e.tvdb_id,'-'),' | ') tvdb_ids,
 group_concat('Emby '||e.emby_id||': '||CASE WHEN e.imdb_id IS NOT NULL THEN e.imdb_id WHEN tx.external_id IS NOT NULL THEN 'TMDB '||e.tmdb_id||' -> '||tx.external_id ELSE '-' END,' | ') imdb_ids
FROM participants p JOIN emby_item e ON e.emby_id=p.person_id LEFT JOIN tmdb_external_id tx ON tx.tmdb_id=e.tmdb_id AND tx.entity_type='person' AND tx.source_name='imdb' GROUP BY p.recommendation_id), media_agg AS (
SELECT p.recommendation_id,group_concat('Emby '||er.person_emby_id||' -> media '||er.media_emby_id||' '||coalesce(m.name,'')||' ['||coalesce(er.person_type,'')||coalesce(': '||er.role,'')||']',' | ') media
FROM participants p JOIN base b ON b.recommendation_id=p.recommendation_id AND b.recommendation_type IN('review-merge','review-split') JOIN emby_relationship er ON er.person_emby_id=p.person_id LEFT JOIN emby_item m ON m.emby_id=er.media_emby_id GROUP BY p.recommendation_id), signal_media AS (
SELECT b.recommendation_id,group_concat(s.evidence_text,' | ') media FROM base b JOIN housekeeping_signal s ON s.run_id=b.run_id AND s.person_emby_id=b.person_emby_id AND (s.provider=b.provider OR b.provider='cross-provider') AND s.media_emby_id IS NOT NULL AND (b.recommendation_type NOT IN('review-split','review-merge') OR s.signal_type LIKE 'confirmed-%') AND (b.provider='cross-provider' OR s.candidate_external_id IS NULL OR (','||coalesce(b.proposed_value,'')||',') LIKE '%,'||s.candidate_external_id||',%' OR b.current_value LIKE '%'||s.candidate_external_id||'%') GROUP BY b.recommendation_id)
SELECT r.recommendation_id,r.person_emby_id,r.person,r.recommendation_type,r.primary_signal_type,r.provider,r.current_value,r.proposed_value,r.confidence,r.linked_media_count,r.checked_media_count,r.evidence_summary,r.review_status,r.participant_ids,
CASE WHEN r.recommendation_type='review-merge' THEN 'Reviewer must select one of: '||r.participant_ids WHEN r.recommendation_type='review-split' THEN r.person_emby_id||' plus new Emby person(s)' ELSE cast(r.person_emby_id AS text) END proposed_emby,
coalesce(i.names,'') current_name,
CASE WHEN r.recommendation_type IN('rename-person','review-existing-emby-person') THEN coalesce(r.proposed_value,'') ELSE coalesce(i.names,'') END proposed_name,
coalesce(i.tmdb_ids,'') current_tmdb,
CASE WHEN r.provider='cross-provider' AND r.recommendation_type='review-split' THEN 'Retain '||coalesce(json_extract(r.proposed_value,'$.retain_tmdb'),'-')||' | Split '||coalesce(json_extract(r.proposed_value,'$.split_tmdb'),'-') WHEN r.provider='tmdb' AND r.recommendation_type='remove-provider-id' THEN '(remove)' WHEN r.provider='tmdb' AND r.recommendation_type IN('replace-provider-id','review-split','review-unresolved-provider-id','provider-person-split-error') THEN coalesce(CASE WHEN r.recommendation_type='provider-person-split-error' THEN r.current_value ELSE r.proposed_value END,'-') WHEN r.provider='tmdb' AND r.recommendation_type='review-merge' THEN coalesce(CASE WHEN instr(r.proposed_value,',')>0 THEN r.current_value ELSE r.proposed_value END,'-') ELSE coalesce(i.tmdb_ids,'') END proposed_tmdb,
coalesce(i.tvdb_ids,'') current_tvdb,
CASE WHEN r.provider='cross-provider' AND r.recommendation_type='review-split' THEN 'Retain '||coalesce(json_extract(r.proposed_value,'$.retain_tvdb'),'-')||' | Split '||coalesce(json_extract(r.proposed_value,'$.split_tvdb'),'-') WHEN r.provider='tvdb' AND r.recommendation_type='remove-provider-id' THEN '(remove)' WHEN r.provider='tvdb' AND r.recommendation_type IN('replace-provider-id','review-split','review-unresolved-provider-id','provider-person-split-error') THEN coalesce(CASE WHEN r.recommendation_type='provider-person-split-error' THEN r.current_value ELSE r.proposed_value END,'-') WHEN r.provider='tvdb' AND r.recommendation_type='review-merge' THEN coalesce(CASE WHEN instr(r.proposed_value,',')>0 THEN r.current_value ELSE r.proposed_value END,'-') ELSE coalesce(i.tvdb_ids,'') END proposed_tvdb,
coalesce(i.imdb_ids,'') current_imdb,CASE WHEN r.provider='cross-provider' AND r.recommendation_type='review-split' THEN 'Retain '||coalesce(json_extract(r.proposed_value,'$.retain_imdb'),'-')||' | Split '||coalesce(json_extract(r.proposed_value,'$.split_imdb'),'-') ELSE coalesce(i.imdb_ids,'') END proposed_imdb,coalesce(sm.media,m.media,'') media
FROM base r LEFT JOIN identity_agg i ON i.recommendation_id=r.recommendation_id LEFT JOIN media_agg m ON m.recommendation_id=r.recommendation_id LEFT JOIN signal_media sm ON sm.recommendation_id=r.recommendation_id ORDER BY r.confidence DESC,r.recommendation_id";using(var s=db.PrepareStatement(sql))foreach(var r in s.ExecuteQuery())a.Add(new HousekeepingResultRow{ProposalId=r.GetInt64(0),EmbyPersonId=r.GetInt64(1),Person=T(r,2),Recommendation=T(r,3),SignalType=T(r,4),Provider=T(r,5),CurrentValue=T(r,6),ProposedValue=T(r,7),Confidence=r.IsDBNull(8)?0:r.GetDouble(8),LinkedMedia=r.IsDBNull(9)?0:r.GetInt(9),CheckedMedia=r.IsDBNull(10)?0:r.GetInt(10),Evidence=T(r,11),ReviewStatus=T(r,12),CurrentEmbyIds=T(r,13),ProposedEmbyIds=T(r,14),CurrentName=T(r,15),ProposedName=T(r,16),CurrentTmdbIds=T(r,17),ProposedTmdbIds=T(r,18),CurrentTvdbIds=T(r,19),ProposedTvdbIds=T(r,20),CurrentImdbIds=T(r,21),ProposedImdbIds=T(r,22),LinkedMediaEvidence=T(r,23)});return a;}
        public string LatestRunSummary(){using(var s=db.PrepareStatement("SELECT 'Latest completed run '||run_id||' | algorithm '||algorithm_version||' | base truth '||base_truth_id||' | observations through '||observation_cutoff_utc||' | completed '||coalesce(completed_utc,'-') FROM housekeeping_run WHERE status='completed' ORDER BY run_id DESC LIMIT 1"))foreach(var r in s.ExecuteQuery())return T(r,0);return "No completed housekeeping run";}
        private void Tx(Action<IDatabaseConnection>a)=>db.RunInTransaction(a,TransactionMode.Immediate);
        private static void State(IDatabaseConnection x,long run,string phase,double progress)=>Exec(x,"UPDATE housekeeping_run SET phase=@p,progress=@n,heartbeat_utc=@now WHERE run_id=@run",s=>{s.TryBind("@p",phase);s.TryBind("@n",progress);s.TryBind("@now",Now());s.TryBind("@run",run);});
        private static void Phase(CancellationToken t,Action<string,double,TimeSpan>r,Stopwatch c,string n,double p){t.ThrowIfCancellationRequested();r?.Invoke(n,p,c.Elapsed);}
        private long Scalar(string sql)=>Scalar(db,sql,s=>{}); private static long Scalar(IDatabaseConnection x,string sql,Action<IStatement>b){using(var s=x.PrepareStatement(sql)){b(s);foreach(var r in s.ExecuteQuery())return r.IsDBNull(0)?0:r.GetInt64(0);}return 0;}
        private static long LastId(IDatabaseConnection x)=>Scalar(x,"SELECT last_insert_rowid()",s=>{}); private static string T(IResultSet r,int i)=>r.IsDBNull(i)?"":r.GetString(i);
        private static void Exec(IDatabaseConnection x,string sql,Action<IStatement>b){using(var s=x.PrepareStatement(sql)){b(s);s.MoveNext();}} private static string Now()=>DateTime.UtcNow.ToString("o"); public void Dispose()=>db.Dispose();
    }
}
